# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 116417608+pharsha9@users.noreply.github.com
author_name: pharsha9
contract_name: contract
deployment_language: python
preset_name: production
project_name: Tokencreator-devtrack-algorandindiasummit-contracts

