# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: 116417608+pharsha9@users.noreply.github.com
author_name: pharsha9
cloud_provider: none
contract_name: contract
deployment_language: python
preset_name: production
project_name: Tokencreator-devtrack-algorandindiasummit

